- include: directory.yml
- include: common.yml

- name: Copy docker and repl scripts
  template:
    src: "{{item}}"
    dest: "/vagrant/mysql-slave/"
    owner: dev-user
    group: dev-user
  with_fileglob:
        - "../../../docker/mysql-slave/docker-compose.yml"
        - "../../../docker/mysql-slave/mysql_connector.sh"

- name: run the service defined in docker-compose.yml
  docker_compose:
    project_src: /vagrant/mysql-slave/

- name: Execute shell for replication
  shell: "docker exec mysqlslave /bin/sh -x /tmp/mysql_connector.sh && ./tmp/mysql_connector.sh"
