- name: Creating user dev with home directory
  become: true
  user: name=dev-user comment="Dev user" createhome="true" home="/home/dev-user"
  #ignore_errors: True

- name: Fixing user ownership
  become: true
  command: chown dev-user:dev-user "/home/dev-user"

- name: Creating  .ssh directory
  become: true
  file: path="/home/dev-user/.ssh" state=directory owner="dev-user"

- name: Fixing user permissions
  become: true
  command: chmod  755 /home/dev-user

- name: Add dev-user user private key
  copy: src=dev-ssh-idrs.private dest=/home/dev-user/.ssh/id_rsa owner=dev-user group=dev-user mode=0600

- name: Add dev-user user public key
  copy: src=dev-ssh-idrs.public dest=/home/dev-user/.ssh/authorized_keys owner=dev-user group=dev-user mode=0600

- name: Add group "docker" for dev-user
  become: true
  group:
    name: docker
    state: present

- name: Add dev-user to group docker
  user:
    name: 'dev-user'
    groups: docker
    append: yes
