version: '2.3'

services:
  redis:
    image: redis:5-alpine
    container_name: redis
    hostname: redis
    privileged: true
    restart: on-failure
    networks:
      - default
    ports:
      - 6379:6379
      - 16379:16379
    volumes:
      - /vagrant/redis/conf/redis.conf:/etc/redis.conf
      - /vagrant/redis/cluster.sh:/usr/local/bin/cluster.sh
    command: /etc/redis.conf


networks:
  default:
    external:
      name: vagrant
