- hosts: all
  become: true

  vars:
    - docker_users:
      - vagrant
    - pip_install_packages:
      - docker
      - docker-compose

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.docker
    - geerlingguy.pip

  tasks:
  # - name: copy Dockerfile
  #   copy:
  #     src: Dockerfile
  #     dest: /vagrant/rabbit/Dockerfile
  #     owner: vagrant
  #     group: vagrant
  #     mode: 644
  #
   # - name: copy docker-compose.yml
   #   copy:
   #     src: ../roles/rabbit/files/docker-compose.yml
   #     dest: /home/vagrant/docker-compose.yml
   #     owner: vagrant
   #     group: vagrant
   #     mode: 644

   - name: Copy scripts kafka env
     template:
       src: "{{item}}"
       dest: "/home/vagrant"
       owner: vagrant
       group: vagrant
       mode: 0644
     with_fileglob:
        - "../roles/rabbit/files/*"
  #
     # pull and build docker images, and start docker-compose
   - name: Run the service defined in docker-compose.yml
     docker_compose:
       project_src: /home/vagrant/
