- hosts: all
  become: true

  vars:
    - docker_users:
      - vagrant
    - pip_install_packages:
      - docker
      - docker-compose

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.docker
    - geerlingguy.pip
    - ../roles/rabbit
