version: '3'
services:
  mysqlslave:
    image: mysql:5.7
    container_name: mysqlslave
    hostname: mysqlslave
    privileged: true
    restart: on-failure
    networks:
      - default
    expose:
      - "3306"
    ports:
      - "3306:3306"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - /vagrant/mysql-slave/conf/etc/mysql/conf.d:/etc/mysql/conf.d
      - mysql_dataslave:/var/lib/mysql
      - /vagrant/mysql-slave/mysql_connector.sh:/tmp/mysql_connector.sh
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - "MYSQL_SLAVE_PASSWORD=root"
      - "MYSQL_MASTER_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"

volumes:
  mysql_dataslave:
    driver: local
    driver_opts:
      type: none
      device: /vagrant/mysql-slave/shared
      o: bind

networks:
  default:
    external:
      name: vagrant
