version: '2.3'

services:
  redis:
    image: redis:5-alpine
    container_name: redis
    hostname: redis
    restart: on-failure
    networks:
      - default
    ports:
      - 6379:6379
    volumes:
      - /vagrant/redis/conf/etc/redis.conf.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf


networks:
  default:
    external:
      name: vagrant
