- name: Copy script
  template:
    src: "{{item}}"
    dest: "/home/vagrant"
    owner: vagrant
    group: vagrant
    mode: 0644
  with_fileglob:
    - docker-compose.yml

- name: Run the service defined in docker-compose.yml
  docker_compose:
    project_src: /home/vagrant/

- name: stop rabbitmq app
  command: docker exec "{{ ansible_hostname }}" /bin/sh -c "rabbitmqctl stop_app"
  when: "ansible_hostname != 'rabbit1'"

- name: add this node to cluster
  command: docker exec "{{ ansible_hostname }}" /bin/sh -c  "rabbitmqctl join_cluster rabbit1@rabbit1"
  when: "ansible_hostname != 'rabbit1'"

- name: start rabbitmq app
  command: docker exec "{{ ansible_hostname }}" /bin/sh -c  "rabbitmqctl start_app"
  when: "ansible_hostname != 'rabbit1'"
