version: '3'
services:
  mysqlmaster:
    image: mysql:5.7
    container_name: mysqlmaster
    hostname: mysqlmaster
    privileged: true
    restart: on-failure
    ports:
      - 3306:3306
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    volumes:
      - /vagrant/mysql/conf:/etc/mysql/conf.d
      - mysql_datamaster:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MASTER_PASS}

volumes:
  mysql_datamaster:
    driver: local
    driver_opts:
      type: none
      device: /vagrant/mysql/data
      o: bind
