version: '3'
services:
  mysqlmaster:
    image: mysql:5.7
    container_name: mysqlmaster
    hostname: mysqlmaster
    privileged: true
    restart: on-failure
    networks:
      - default
    expose:
      - "3306"
    ports:
      - "3306:3306"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - /vagrant/mysql-master/conf/etc/mysql/conf.d:/etc/mysql/conf.d
      - mysql_datamaster:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysql_datamaster:
    driver: local
    driver_opts:
      type: none
      device: /vagrant/mysql-master/shared
      o: bind

networks:
  default:
    external:
      name: vagrant
